networks:
  dev:

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8083:8083"
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "81:81"
    depends_on:
      - backend
    networks:
      - dev